# Generated by Django 4.2.4 on 2023-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.TextField(blank=True, max_length=50, null=True)),
                ('mac_address', models.IntegerField(blank=True, max_length=50, null=True)),
                ('ip_address', models.IntegerField(blank=True, max_length=50, null=True)),
                ('unit', models.TextField(blank=True, max_length=50, null=True)),
                ('location', models.TextField(blank=True, max_length=50, null=True)),
                ('added_by', models.TextField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('updated_by', models.TextField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
