# Generated by Django 4.2.4 on 2023-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='ip_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mac_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
