# Generated by Django 4.2.4 on 2023-10-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date | mm-dd-yy')),
                ('csv_export', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Os_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_system', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Computers',
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.os_choice'),
        ),
    ]
