# Generated by Django 4.2.4 on 2023-10-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_computers_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
    ]
