# Generated by Django 4.2.4 on 2023-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_computer_os_choice_delete_computers_computer_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='os',
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ManyToManyField(blank=True, null=True, to='Inventory.os_choice'),
        ),
    ]
