# Generated by Django 4.2.4 on 2023-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_computer_os_computer_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='csv_export',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.ManyToManyField(null=True, to='Inventory.os_choice'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='Purchase Date | mm-dd-yy'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
