# Generated by Django 4.2.4 on 2023-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_computer_added_by_alter_computer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='added_by',
            new_name='os',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='unit',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
