# Generated by Django 4.2.4 on 2023-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_computer_csv_export_alter_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Leave Date Blank'),
        ),
    ]
