# Generated by Django 4.2.4 on 2023-10-06 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Update Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 6, 11, 26, 39, 643753, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
