# Generated by Django 4.2.4 on 2023-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_rename_added_by_computer_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
