# Generated by Django 4.2.4 on 2023-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='csv_export',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
