# Generated by Django 4.2.4 on 2023-10-07 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_computer_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('IP_address', models.CharField(blank=True, max_length=30, null=True)),
                ('MAC_address', models.CharField(blank=True, max_length=30, null=True)),
                ('users_name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='Update Date (mm/dd/yyyy)')),
                ('purchase_date', models.DateField()),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.os_choice')),
            ],
        ),
    ]
