# Generated by Django 4.2.4 on 2023-10-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_computerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerhistory',
            name='os',
        ),
    ]
