# Generated by Django 4.2.4 on 2023-10-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_computerhistory_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerhistory',
            old_name='IP_address',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='computerhistory',
            old_name='MAC_address',
            new_name='mac_address',
        ),
        migrations.RenameField(
            model_name='computerhistory',
            old_name='computer_name',
            new_name='pc_name',
        ),
        migrations.RenameField(
            model_name='computerhistory',
            old_name='users_name',
            new_name='username',
        ),
    ]
